// Agent Toolkit — OpenCode Plugin
// Auto-generated by scripts/converter.py --opencode
// Do not edit manually — regenerate with `npm run convert:opencode`

const agents = [
  "accessibility",
  "architect",
  "brainstorming",
  "browser-automator",
  "build-error-resolver",
  "code-reviewer",
  "database-reviewer",
  "doc-updater",
  "e2e-runner",
  "explorer",
  "fastapi-reviewer",
  "loop-operator",
  "performance-optimizer",
  "planner",
  "python-reviewer",
  "react-reviewer",
  "refactor-cleaner",
  "security-reviewer",
  "senior-fullstack",
  "senior-ux",
  "subagent-driven-dev",
  "systematic-debugging",
  "tdd-guide",
  "typescript-reviewer",
  "verification-before-completion",
  "writing-plans"
];
const skills = [
  "agent-eval",
  "ai-coding-agents",
  "api-design",
  "architecture-decision-records",
  "backend-patterns",
  "brainstorming",
  "browser-use",
  "codebase-onboarding",
  "context-budget",
  "continuous-learning-v2",
  "deep-paper-note",
  "executing-plans",
  "finishing-a-development-branch",
  "frontend-a11y",
  "frontend-design-direction",
  "frontend-patterns",
  "ralphex",
  "react-patterns",
  "react-performance",
  "react-testing",
  "receiving-code-review",
  "reflect",
  "requesting-code-review",
  "security-review",
  "subagent-driven-development",
  "systematic-debugging",
  "tdd-workflow",
  "test-driven-development",
  "using-git-worktrees",
  "verification-before-completion",
  "vvveb-js",
  "web-security-essentials",
  "writing-plans",
  "writing-skills"
];
const commands = [
  {
    "name": "build-fix",
    "description": "Diagnose and fix build/type errors"
  },
  {
    "name": "code-review",
    "description": "Run a comprehensive code review on recent changes"
  },
  {
    "name": "learn",
    "description": "Continuous learning from feedback patterns"
  },
  {
    "name": "plan",
    "description": "Create an implementation plan for a task"
  },
  {
    "name": "quality-gate",
    "description": "Run quality checks before committing"
  },
  {
    "name": "reflect",
    "description": "Extract learnings from the current session"
  },
  {
    "name": "security-scan",
    "description": "Quick security scan for common vulnerabilities"
  },
  {
    "name": "tdd",
    "description": "Start a TDD workflow (RED-GREEN-REFACTOR)"
  }
];

function listAllSkills() { return skills; }
function listAllAgents() { return agents; }
function listCommands() { return commands; }
function getSkillCount() { return skills.length; }
function getAgentCount() { return agents.length; }
function getCommandCount() { return commands.length; }

module.exports = {
  agents,
  skills,
  commands,
  listAllSkills,
  listAllAgents,
  listCommands,
  getSkillCount,
  getAgentCount,
  getCommandCount,
};
